### ISSUE TITLE
Sphinx Markdown MathJax doesn't work correctly

### ISSUE THREAD

**Issue by zjZSTU** [readthedocs/recommonmark#133]
**Describe the bug**
1. use sphinx-quickstart create a new project，add the **mathjax support**
2. Reference to official documents for **markdown**: [Markdown](https://www.sphinx-doc.org/en/master/usage/markdown.html?highlight=markdown)
3. in markdown.md files，MathJax doesn't work correclty 
          3.1 the Inline Notes on Math Formula $...$ doesn't work
          3.2 if there are several rows math formula， $$...$$, doesn't work

**To Reproduce**

step1: $f(\tau )$ can't work fine
step2: The following mathematical formulas can't be displayed correctly either.

$$
f(\tau )
f(\tau )
f(\tau )
$$

**Your project**

page 1: [Markdown使用-5 数学公式](https://zj-markdown-guide.readthedocs.io/zh/latest/Markdown%E4%BD%BF%E7%94%A8-5-%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F.html)
page2: [充分条件-必要条件](https://zj-computer-foundation.readthedocs.io/zh_CN/latest/maths/%E5%85%85%E5%88%86%E6%9D%A1%E4%BB%B6-%E5%BF%85%E8%A6%81%E6%9D%A1%E4%BB%B6.html)

**Environment info**

- OS: Ubuntu 16.04
- Python version: 3.7.1
- Sphinx version: 1.8.2
- Sphinx extensions:  sphinx.ext.mathjax, recommonmark

**Comment by rsyi** [comment]
I've come across this same problem as well, and noticed that the directive and role mathjax notations still work in .rst files... 

I think there was some sort of recent update, as the docs now say:
> Attention
> 
> You should use the math directive and role, not the native MathJax $$, \(, etc.

(See [here](https://www.sphinx-doc.org/en/master/usage/extensions/math.html).)

**Comment by zjZSTU** [comment]
> I've come across this same problem as well, and noticed that the directive and role mathjax notations still work in .rst files...
> 
> I think there was some sort of recent update, as the docs now say:
> 
> > Attention
> > You should use the math directive and role, not the native MathJax $$, (, etc.
> 
> (See [here](https://www.sphinx-doc.org/en/master/usage/extensions/math.html).)

thank you for you reply.  I checked the official documents just now. As you said, there is no effective solution for markdown mathjax. .rst file is more supported by sphinx

**Comment by AndrewBelt** [comment]
I don't know if this is a fluke, but I was able to trigger the Mathjax parser to run on Markdown pages by adding a single math formula to my `index.rst` page. (You must write the index in reStructuredText every other page can be Markdown.) The math formula can be blank, e.g.

```rst
.. math::
```

**Comment by ZqIceberg** [comment]
> I don't know if this is a fluke, but I was able to trigger the Mathjax parser to run on Markdown pages by adding a single math formula to my `index.rst` page. (You must write the index in reStructuredText every other page can be Markdown.) The math formula can be blank, e.g.
> 
> ```
> .. math::
> ```

thank u for your suggestion, it works! But, I come to new situation. In Marddown, $$ $$ can work, but $ $ (in line notes does not work). Do you have same situation?

**Comment by caniko** [comment]
> > I don't know if this is a fluke, but I was able to trigger the Mathjax parser to run on Markdown pages by adding a single math formula to my `index.rst` page. (You must write the index in reStructuredText every other page can be Markdown.) The math formula can be blank, e.g.
> > ```
> > .. math::
> > ```
> 
> thank u for your suggestion, it works! But, I come to new situation. In Marddown, $$ $$ can work, but $ $ (in line notes does not work). Do you have same situation?

Have you tried using `role` for inline math? Like this for example (from the [docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-math)):
```
:math:`a^2 + b^2 = c^2`
```
