### ISSUE TITLE
Breakage from 0.4.0 to 0.5.0

### ISSUE THREAD

**Issue by pawamoy** [readthedocs/recommonmark#146]
#### With version 0.4.0 and

```python
source_suffix = [".rst", ".md"]
source_parsers = {".md": "recommonmark.parser.CommonMarkParser"}
```

Works fine, markdown files are added to the build.

#### With version 0.5.0 and

```python
source_suffix = [".rst", ".md"]
source_parsers = {".md": "recommonmark.parser.CommonMarkParser"}
```

```
Extension error:
source_parser for 'md' is already registered
```

#### With version 0.5.0 and 

```python
source_suffix = [".rst", ".md"]
# source_parsers = {".md": "recommonmark.parser.CommonMarkParser"}
```

Markdown files not added:

```
checking consistency... /media/Data/dev/pawamoy/aria2p/docs/changelog.md: WARNING: document isn't included in any toctree
/media/Data/dev/pawamoy/aria2p/docs/code_of_conduct.md: WARNING: document isn't included in any toctree
/media/Data/dev/pawamoy/aria2p/docs/configuration.md: WARNING: document isn't included in any toctree
/media/Data/dev/pawamoy/aria2p/docs/contributing.md: WARNING: document isn't included in any toctree
/media/Data/dev/pawamoy/aria2p/docs/credits.md: WARNING: document isn't included in any toctree
/media/Data/dev/pawamoy/aria2p/docs/readme.md: WARNING: document isn't included in any toctree
/media/Data/dev/pawamoy/aria2p/docs/usage.md: WARNING: document isn't included in any toctree
```

**Comment by stsewd** [comment]
I'm guessing the sphinx version is the problem, you should use 

```
extensions = ['recommonmark']
```

For sphinx >= 1.4

**Comment by pawamoy** [comment]
Sorry, I forgot to precise, I already have "recommonmark" in the `extensions` list.

**Comment by stsewd** [comment]
Can you link to the project? Or a reproducible project?

**Comment by pawamoy** [comment]
Of course: [aria2p](https://github.com/pawamoy/aria2p)

You'll need [poetry](https://github.com/sdispater/poetry).

```
git clone https://github.com/pawamoy/aria2p
cd aria2p
poetry install

make docs  # should work

poetry run pip install recommonmark==0.5.0
make docs  # error above
```

**Comment by pawamoy** [comment]
Hi again, it seems recommonmark 0.5.0 is now installed by default on readthedocs. It forces me to pin recommonmark==0.4.0 in a requirements.txt file (mine is docs/requirements.txt).

Have you had any time to take a look at the issue?

I created a new repository to reproduce the issue at https://github.com/pawamoy/repro-recommonmark-146.

**Comment by cas--** [comment]
> source_parser for 'md' is already registered

Seems to be a misreading of the changes in Sphinx 1.8 where *source_**parsers*** has been replaced by a *source_**suffix*** dict. So the change for Sphinx 1.8 and recommonmark 0.5 should be:

```diff
 # Documentation in Markdown
-source_suffix = [".rst"]
-source_parsers = {".md": "recommonmark.parser.CommonMarkParser"}
+source_suffix = {
+    '.rst': 'restructuredtext',
+    '.md': 'markdown',
+}
```
It wasn't immediately obvious to me and hope that helps

**Comment by pawamoy** [comment]
A-ha! It seems the culprit was in fact `url_resolver`. Trying your fix only did not work, but when I also commented the `url_resolver` line, it worked.

```diff
# Documentation in Markdown
-source_suffix = [".rst"]
-source_parsers = {".md": "recommonmark.parser.CommonMarkParser"}
+source_suffix = [".rst", ".md"]

@ conf.py:39 @ def setup(app):
-            "url_resolver": lambda url: doc_root + url,
+            #"url_resolver": lambda url: doc_root + url,
```

**Comment by pawamoy** [comment]
Based on the docs:

> **Auto Doc Ref** 
*This option is deprecated.* This option has been superseded by the default linking behavior, which will first try to resolve as an internal reference, and then as an external reference.

So, shouldn't my markdown files be resolved internally first, and then externally to GitHub (with `url_resolver`)? It seems it's doing the opposite, since keeping the `url_resolver` line uncommented results in these two warnings:

> /media/Data/dev/pawamoy/repro-recommonmark-146/docs/contributing.md: WARNING: document isn't included in any toctree
/media/Data/dev/pawamoy/repro-recommonmark-146/docs/readme.md: WARNING: document isn't included in any toctree

...and the links in the generated docs then point to GitHub (with a 404).

**Comment by pawamoy** [comment]
Closing in favor of https://github.com/readthedocs/recommonmark/issues/137
