### ISSUE TITLE
Tests breaks with Sphinx 2.0+

### ISSUE THREAD

**Issue by Jenselme** [readthedocs/recommonmark#164]
Two tests breaks because with Sphinx 2.0, `p` tag is added where is shouldn't:
- `tests.test_sphinx.GenericTests testMethod=test_lists` breaks because instead of `<ul class="simple">\n<li>Item A</li>\n<li>Item B</li>\n<li>Item C</li>\n</ul>` we have `<ul class="simple">\n<li><p>Item A</p></li>\n<li><p>Item B</p></li>\n<li><p>Item C</p></li>\n</ul>` with extra `p`.
- `tests.test_sphinx.CustomExtensionTests testMethod=test_integration` because instead of `<th class="head">abc</th>` we have `<th class="head"><p>abc</p></th>`.

Can you fix this and add Sphinx 2.0 support?

**Comment by gibfahn** [comment]
FWIW this module works fine with Sphinx 2.1.2 for my project.
