### ISSUE TITLE
Support for literalinclude?

### ISSUE THREAD

**Issue by feluxe** [readthedocs/recommonmark#168]
Hi there!

I couldn't find anything in the docs and I don't know where else to ask, so I thought I give it a shot here.

In sphinx with reStructuredText, you can use `literalinclude` to include code sections from other files in the doc pages, which is really useful. E.g.:

```
.. literalinclude:: ../../tests/docs/getting_started.py
   :language: py
   :start-after: foo...
   :end-before: bar...
```

I wonder if something similar would be possible with `recommonmark`?

Thanks in advance :)

**Comment by drupol** [comment]
I'd like to see this thing as well.
