### ISSUE TITLE
parser: improve error reporting and handling of newlines in visit_image()

### ISSUE THREAD

**Issue by drrosa** [readthedocs/recommonmark#176]
The upgrade to version `0.6.0` resulted in what appeared to be a `sphinx-build` error shown as `TypeError: sequence item 1: expected str instance, NoneType found`. But it turned out to be a parsing error caused by a single newline character in the alt text of an inline-style image link.

I was able to find the newline after adding a couple of print statements as shown below which showed the alt-text and the file where the issue was coming from.

```python
    def visit_image(self, mdnode):
        img_node = nodes.image()
        img_node['uri'] = mdnode.destination

        if mdnode.first_child and mdnode.first_child.literal:
            content = [mdnode.first_child.literal]
            print("BEFORE", content)
            n = mdnode.first_child
            mdnode.first_child.literal = ''
            mdnode.first_child = mdnode.last_child = None
            while getattr(n, 'nxt'):
                n.nxt, n = None, n.nxt
                content.append(n.literal)
            print("AFTER", content)
            img_node['alt'] = ''.join(content)

        self.current_node.append(img_node)
        self.current_node = img_node
```

For more details see https://github.com/zulip/zulip/pull/13241.

**Comment by pvgenuchten** [comment]
I confirm, also mistakingly posted [here](https://github.com/sphinx-doc/sphinx/issues/6797)
