### ISSUE TITLE
Push git tags to GitHub

### ISSUE THREAD

**Issue by jezdez** [readthedocs/recommonmark#19]
I wasn't sure when the `AutoStructify` stuff was added and couldn't easily find which commit was released.

**Comment by lorengordon** [comment]
👍 pretty please.

**Comment by neok-m4700** [comment]
Up on this one, pretty useful !

**Comment by pawamoy** [comment]
Yes, I wanted to see the difference between 0.4.0 and 0.5.0 (because of #146) and it's not possible here.
