### ISSUE TITLE
Github edit link using wrong source file suffix

### ISSUE THREAD

**Issue by chuan92** [readthedocs/recommonmark#20]
When I click 'Edit on Github' at http://recommonmark.readthedocs.org/en/latest/, it links to 'index.rst' not 'index.md', and results a '404error'. It seems all links to '.md' now are '.rst' wrongly.

This also happens in mxnet(http://mxnet.readthedocs.org/en/latest/) doc which uses this package.

**Comment by brianjking** [comment]
@rtfd - Same here. Any updates?

Thanks!

**Comment by Gohla** [comment]
This is fixed by updating to [Sphinx 1.3.6](http://www.sphinx-doc.org/en/stable/changes.html#release-1-3-6-released-feb-29-2016)

**Comment by JimiC** [comment]
We solved this by changing the order of `source_suffix` in `conf.py` to `source_suffix = ['.md', '.rst']`
