### ISSUE TITLE
Linking to .py file from a markdown files gives a warning: "any reference target not found"

### ISSUE THREAD

**Issue by GiliR4t1qbit** [readthedocs/recommonmark#216]
I've got a `README.md` with a relative link to a .py file, like this:
```
[main script](main.py)
```
When building the docs to html I get this warning:
```python
/Users/XXXX/git/XXXX/docs/source/XXXX/README.md:124: WARNING: None:any reference target not found: main.py
```

I make sure that the .py file is in the right location, and in the final HTML, the link does actually work! So, what's the problem then? Well, I need my build to be clear of warnings, so that I can use the `-W` flag, so that important warnings are raised and caught as errors. 

I still get a warning if I use `./main.py` in the link, but I don't get a warning if I point the relative link to a markdown file instead. So, I suspect that there is some mechanism that allows only links to files with specific extensions? But if I add `".py"` to the `source_suffix` list then I get a bunch of errors since I think the .py files are then parsed as markdown. I know there's also an option of providing a `dict` for `source_suffix`, but I'm not sure what value to map the `".py"` extension/key to. I thought of writing my own parser, but there has to be a simpler solution...

The docs mention:

> For all links in commonmark that aren’t explicit URLs, they are treated as cross references with the :any: role. This allows referencing a lot of things including files, labels, and even objects in the loaded domain.

which led me to think that links to files should work out of the box...?

(note: I'm not sure this is an issue with `recommonmark`, but I think it might be due to it seemingly being an issue with cross-referencing)

**Comment by maglo** [comment]
Same here, but for a JSON file:

`[package-lock.json](package-lock.json)`

I have added to my `conf.py`

```
import recommonmark
from recommonmark.transform import AutoStructify

...

def setup(app):
    app.add_config_value('recommonmark_config', {
            'url_resolver': lambda url: 'https://NTERNAL_URL/' + url,
            'auto_toc_tree_section': 'Contents',
            }, True)
    app.add_transform(AutoStructify)
```
