### ISSUE TITLE
AttributeError: 'Values' object has no attribute 'tab_width'

### ISSUE THREAD

**Issue by probonopd** [readthedocs/recommonmark#220]
Continuation from https://github.com/sphinx-doc/sphinx/issues/9049

```
+ make html
Running Sphinx v3.5.3
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 51 source files that are out of date
updating environment: [new config] 51 added, 0 changed, 0 removed
reading sources... [  1%] developer/acknowledgements
reading sources... [  3%] developer/application-bundles
/usr/local/lib/python3.8/dist-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))

Exception occurred:
  File "/usr/local/lib/python3.8/dist-packages/docutils/parsers/rst/__init__.py", line 193, in parse
    inputstring, tab_width=document.settings.tab_width,
AttributeError: 'Values' object has no attribute 'tab_width'
The full traceback has been saved in /tmp/sphinx-err-2f_3sdun.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

* https://github.com/helloSystem/docs/tree/9de4b3c6ab32e242ea263915b70a33366d3348ac
* https://github.com/helloSystem/docs/runs/2259870252?check_suite_focus=true

Workaround:
Pinning docutils to 0.16:
`pip3 install docutils==0.16 sphinx ...`. Thanks @zmey3301

@k0miya [says](https://github.com/sphinx-doc/sphinx/issues/9049#issuecomment-812959667):

> It seems the error happened inside the recommonmark extension. I guess this is a bug of it. The tab_width entry is needed for the settings_spec of the recommonmark parser.

**Comment by gmilde** [comment]
To better integrate into Docutils, the recommonmark.parser.CommonMarkParser should add the lines

        config_section = 'recommonmark parser'
        config_section_dependencies = ('parsers',)

to the class attributes.
If the extension to parse included rST is active, consider allowing configuration of the rst parser, e.g.:

        config_section = 'recommonmark parser'
        config_section_dependencies = ('parsers', 'restructuredtext parser')

**Comment by astrojuanlu** [comment]
Notice that recommonmark has been deprecated in favor of MyST-Parser, which is almost a drop-in replacement https://github.com/readthedocs/recommonmark/issues/221
