### ISSUE TITLE
How about new release 0.4.x?

### ISSUE THREAD

**Issue by shimizukawa** [readthedocs/recommonmark#38]
Latest release of the recommonmark is 0.4.0 at 2016-01-05: https://pypi.python.org/pypi/recommonmark/0.4.0

Do you have any release plan?

**Comment by ibigbug** [comment]
same issue

**Comment by chrysn** [comment]
Even if you can't push a release for whichever reasons, at least increment the version number in master.

That way, whoever is eg. struck by the incompatibility of 0.4.0 with sphinx-argparse (requiring commonmark <= 0.5.4 and commonmark >= 0.5.6, respectively) can add a `requirements.txt` file saying `git+https://github.com/rtfd/recommonmark.git#egg=recommonmark > 0.4.0` to their project. While the master version still says 0.4.0, no upgrade can be enforced from requirements.txt AFAICT.

(And still, please push a release, so those workarounds won't be necessary at all).

**Comment by chrysn** [comment]
A `requirements.txt` file with `-e git+https://github.com/rtfd/recommonmark.git#egg=recommonmark` works just as well as a bumped version; my previous comment is thus moot. Thanks agj for pointing this out to me.

**Comment by tdomhan** [comment]
thanks for the tip! That said, it would still be nice to get a new version on PyPI.
