### ISSUE TITLE
Shorthand style for embedding reStructuredText not working

### ISSUE THREAD

**Issue by gxclarke** [readthedocs/recommonmark#51]
I'm finding that the long-hand version for embedding reStructuredText works fine, but the short-hand version doesn't get processed so it is instead rendered as a regular code block. For example...

``````
    ## Works Perfectly

    ```eval_rst
    .. important:: It's a note! in markdown!
    ```

    ## Does Not Work

    ``` important:: It's a note! in markdown!
    ```
``````

The compiler reports the following for the line with the short-hand synax:

```
WARNING: Pygments lexer name u'important:: Its a note! in markdown!' is not known
```

**Comment by thfanning** [comment]
I ran into this problem too. It turns out that the version you get from `pip install recommonmark` (see https://pypi.python.org/pypi/recommonmark/0.4.0) does not have the code updates that implement this. You'll need to clone from GitHub.

To the maintainers: please update the package on PyPI.

**Comment by mlncn** [comment]
And the version running on ReadTheDocs.org?
