### ISSUE TITLE
included markdown documents are parsed as rst

### ISSUE THREAD

**Issue by anarcat** [readthedocs/recommonmark#54]
I have tried the recommonmark plugin locally and on RTFD.org, and it seems to fail fairly basic Commonmark markup:

http://monkeysign.readthedocs.io/en/latest/

Notice how the following tags are not parsed properly:
- `### Requirements` header
- code blocks (`apt-get install monkeysign` is rendered in a `<blockquote>`)
- links (`[OpenKeychain][]` and others)

All this works fine on the standard Commonmark tester here:

http://spec.commonmark.org/dingus/

[direct link](http://spec.commonmark.org/dingus/?text=Monkeysign%3A%20OpenPGP%20Key%20Exchange%20for%20Humans%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%0Amonkeysign%20is%20a%20tool%20to%20overhaul%20the%20OpenPGP%20keysigning%20experience%20and%0Abring%20it%20closer%20to%20something%20that%20most%20primates%20can%20understand.%0A%0AThe%20project%20makes%20use%20of%20cheap%20digital%20cameras%20and%20the%20type%20of%20bar%0Acode%20known%20as%20a%20QRcode%20to%20provide%20a%20human-friendly%20yet%20still-secure%0Akeysigning%20experience.%0A%0ANo%20more%20reciting%20tedious%20strings%20of%20hexadecimal%20characters.%20And%2C%20you%0Acan%20build%20a%20little%20rogue%27s%20gallery%20of%20the%20people%20that%20you%20have%20met%20and%0Aexchanged%20keys%20with!%20%28Well%2C%20not%20yet%2C%20but%20it%27s%20part%20of%20the%20plan.%29%0A%0AMonkeysign%20also%20features%20a%20user-friendly%20commandline%20tool%2C%20similar%20to%0A%60caff%60%2C%20to%20sign%20OpenGPG%20keys%20following%20the%20current%20best%20practices.%0A%0AMonkeysign%20was%20written%20by%20Jerome%20Charaoui%20and%20Antoine%20Beaupr%C3%A9%20and%20is%0Alicensed%20under%20GPLv3.%0A%0AFeatures%0A---------%0A%0A%20*%20commandline%20and%20GUI%20interface%0A%20*%20GUI%20supports%20exchanging%20fingerprints%20with%20qrcodes%0A%20*%20print%20your%20OpenPGP%20fingerprint%20on%20a%20QRcode%0A%20*%20key%20signature%20done%20on%20a%20separate%20keyring%0A%20*%20signature%20sent%20in%20a%20crypted%20email%20to%20ensure%3A%0A%20%20%201.%20the%20signee%20controls%20the%20signed%20email%0A%20%20%202.%20the%20signee%20controls%20the%20private%20key%0A%20%20%203.%20the%20signee%20decides%20what%20to%20do%20with%20the%20signature%0A%20*%20local%20%28%22non-exportable%22%29%20signatures%0A%20*%20send%20through%20local%20email%20server%2C%20arbitrary%20SMTP%20server%20or%20other%0A%20%20%20programs%0A%0AInstalling%0A----------%0A%0AMonkeysign%20should%20be%20available%20in%20Debian%20and%20Ubuntu%2C%20but%20can%20also%0Aeasily%20be%20installed%20from%20source.%0A%0A%23%23%23%20Requirements%0A%0AThe%20following%20Python%20packages%20are%20required%20for%20the%20GUI%20to%20work.%0A%0A%20%20%20%20python-qrencode%20python-gtk2%20python-zbar%20python-zbarpygtk%0A%0AIf%20they%20are%20not%20available%2C%20the%20commandline%20signing%20tool%20should%20still%0Awork%20but%20doesn%27t%20recognize%20QR%20codes.%0A%0AOf%20course%2C%20all%20this%20depends%20on%20the%20GnuPG%20program.%0A%0A%23%23%23%20In%20Debian%20%2F%20Ubuntu%0A%0AMonkeysign%20is%20now%20in%20Debian%2C%20since%20Jessie%20%28and%20backported%20to%20Wheezy%29%0Aand%20Ubuntu%20%28since%20Trusty%2014.04LTS%29.%20To%20install%20it%2C%20just%20run%3A%0A%0A%20%20%20%20apt-get%20install%20monkeysign%0A%0A%23%23%23%20From%20git%0A%0AYou%20can%20fetch%20monkeysign%20with%20git%3A%0A%0A%20%20%20%20git%20clone%20git%3A%2F%2Fgit.monkeysphere.info%2Fmonkeysign%0A%0A%23%23%23%20From%20source%0A%0AThe%20source%20tarball%20is%20also%20available%20directly%20from%20the%20Debian%20mirrors%0Ahere%3A%0A%0A%20%20%20%20http%3A%2F%2Fcdn.debian.net%2Fdebian%2Fpool%2Fmain%2Fm%2Fmonkeysign%2F%0A%0AThe%20%60.tar.gz%60%20file%20has%20a%20checksum%2C%20cryptographically%20signed%2C%20in%20the%0A%60.dsc%60%20file.%0A%0A%23%23%23%20Installing%20from%20source%0A%0ATo%20install%20monkeysign%2C%20run%3A%0A%0A%20%20%20%20sudo%20.%2Fsetup.py%20install%20--record%3Dinstall.log%0A%0ARunning%0A-------%0A%0AThe%20graphical%20interface%20should%20be%20self-explanatory%2C%20it%20should%20be%20in%0Ayour%20menus%20or%20call%20it%20with%3A%0A%0A%20%20%20%20monkeyscan%0A%0AThe%20commandline%20interface%20should%20provide%20you%20with%20a%20complete%20help%20file%0Awhen%20called%20with%20%60--help%60%3A%0A%0A%20%20%20%20monkeysign%20--help%0A%0AFor%20example%2C%20to%20sign%20a%20given%20fingerprint%3A%0A%0A%20%20%20%20monkeysign%2090ABCDEF1234567890ABCDEF1234567890ABCDEF%0A%0AThis%20will%20fetch%20the%20key%20from%20your%20keyring%20%28or%20a%20keyserver%29%20and%20sign%20it%0Ain%20a%20temporary%20keyring%2C%20then%20encrypt%20the%20signature%20and%20send%20it%20in%20an%0Aemail%20to%20the%20owner%20of%20the%20key.%0A%0ACaveats%0A-------%0A%0A%20*%20There%20are%20numerous%20bugs%20with%20odd%20keys%20and%20GnuPG%20corner%20cases.%20Most%0A%20%20%20of%20them%20should%20be%20documented%20on%20the%20Debian%20BTS%20here%3A%0A%20%20%20https%3A%2F%2Fbugs.debian.org%2Fmonkeysign%0A%0A%20*%20Running%20monkeysign%20in%20%60--debug%60%20mode%20and%20sending%20the%20output%20to%20a%0A%20%20%20public%20forum%20may%20leak%20public%20or%20even%20private%20key%20material%20in%20some%0A%20%20%20circumstances.%20Special%20efforts%20have%20been%20made%20so%20that%20private%20key%0A%20%20%20material%20is%20never%20output%20to%20the%20screen%2C%20but%20you%20can%20never%20be%20too%0A%20%20%20careful%3A%20look%20at%20the%20output%20before%20you%20send%20it.%0A%0A%20*%20The%20graphical%20interface%20isn%27t%20as%20complete%20as%20the%20commandline.%20A%20few%0A%20%20%20features%20are%20missing%20and%20it%20is%20mostly%20a%20proof%20of%20concept%20at%20this%0A%20%20%20point%20which%20works%2C%20but%20has%20a%20few%20rough%20edges.%20In%20particular%2C%20if%20you%0A%20%20%20have%20a%20high%20resolution%20camera%2C%20the%20camera%20window%20may%20fill%20your%0A%20%20%20screen%20completely%2C%20in%20which%20case%20you%20may%20want%20to%20change%20the%0A%20%20%20resolution%20beforehand%20using%20the%20following%20commands%3A%0A%0A%20%20%20%20%20%20%20%20sudo%20apt-get%20install%20v4l-utils%0A%20%20%20%20%20%20%20%20v4l2-ctl%20--set-fmt-video%3Dwidth%3D640%2Cheight%3D480%2Cpixelformat%3D1%0A%0A%20%20%20See%20https%3A%2F%2Fbugs.debian.org%2Fcgi-bin%2Fbugreport.cgi%3Fbug%3D723154%20for%0A%20%20%20more%20information%20about%20this%20specific%20problem.%0A%0A%20*%20Both%20the%20graphical%20and%20commandline%20interface%20assume%20you%20are%20fairly%0A%20%20%20familiar%20with%20SMTP%20configuration%20or%20had%20an%20administrator%20setup%20a%0A%20%20%20mailserver%20on%20your%20machine%20for%20email%20delivery.%0A%0ASupport%0A-------%0A%0ADiscussions%2C%20questions%20and%20issues%20can%20be%20brought%20up%20on%20the%20mailing%0Alist%2C%20%3Cmonkeysphere%40lists.riseup.net%3E.%20See%20the%20%5BCONTRIBUTING.md%5D%5B%5D%0Afile%20for%20more%20information%20about%20how%20to%20file%20bugs.%0A%0A%5BCONTRIBUTING.md%5D%3A%20CONTRIBUTING.md%0A%0ASimilar%20projects%0A----------------%0A%0A%20*%20%5BOpenKeychain%5D%5B%5D%2C%20a%20fork%20of%20%5BAPG%5D%5B%5D%2C%20has%20support%20for%20exporting%20and%0A%20%20%20importing%20fingerprints%20in%20QRcode%20and%20NFC.%20It%20uses%20similar%20strings%0A%20%20%20for%20QRcodes%20exchanges%20and%20is%20compatible%20with%0A%20%20%20Monkeysign.%20%28%5BGithub%20project%5D%5B2%5D%29%0A%0A%20%5BOpenKeychain%5D%3A%20https%3A%2F%2Fwww.openkeychain.org%2F%0A%20%5BAPG%5D%3A%20http%3A%2F%2Fwww.thialfihar.org%2Fprojects%2Fapg%2F%0A%20%5B2%5D%3A%20https%3A%2F%2Fgithub.com%2Fopen-keychain%2Fopen-keychain%0A%0A%20*%20%5BGPG%20for%20Android%5D%5B%5D%20%28of%20the%20%5BGuardian%20project%5D%5B%5D%29%20will%20import%0A%20%20%20public%20keys%20in%20your%20device%27s%20keyring%20when%20they%20are%20found%20in%0A%20%20%20QRcodes%2C%20so%20it%20should%20be%20able%20to%20talk%20with%20Monkeysign%2C%20but%20this%0A%20%20%20remains%20to%20be%20tested.%20%28%5BGithub%20project%5D%5B%5D%29%0A%20%0A%20%5BGPG%20for%20Android%5D%3A%20https%3A%2F%2Fguardianproject.info%2Fcode%2Fgnupg%2F%0A%20%5BGuardian%20project%5D%3A%20https%3A%2F%2Fguardianproject.info%2F%0A%20%5BGithub%20project%5D%3A%20https%3A%2F%2Fgithub.com%2Fguardianproject%2Fgnupg-for-android%0A%0A%20*%20%5BGibberbot%5D%5B%5D%20%28also%20of%20the%20%5BGuardian%20project%5D%5B%5D%29%20can%20exchange%20OTR%0A%20%20%20fingerprints%20using%20QRcodes.%20%28%5BGithub%20project%5D%5B3%5D%29%0A%0A%20%5BGibberbot%5D%3A%20https%3A%2F%2Fguardianproject.info%2Fapps%2Fgibber%2F%0A%20%5B3%5D%3A%20https%3A%2F%2Fgithub.com%2Fguardianproject%2FGibberbot%0A)

is this a bug in [commonmark.py](https://github.com/rtfd/CommonMark-py) or am i doing something wrong?

**Comment by anarcat** [comment]
obviously, i was doing something wrong: it's an include from a .rst file... but the question still stands - is this a desirable feature?

**Comment by vmuriart** [comment]
Just ran into the same problem/question. Looks like the best solution is to use `symlinks` to the files you want. You can see an example on the [recommonmark documentation files](https://github.com/rtfd/recommonmark/blob/master/docs/index.md)

**Comment by arximboldi** [comment]
I run into this issue today and found this alternative to `recommonmark` which fixes the issue by providing an alternative `.. mdinclude` directive to include Markdown documents.

**Comment by bilderbuchi** [comment]
@arximboldi I have the same problem. Which package does that (you just say "this")?

**Comment by arximboldi** [comment]
@bilderbuchi sorry I didn't realize I didn't paste a link. I think the project was this one: https://github.com/miyakogi/m2r

Admittedly, in the end I just submitted to getting used to RST everywhere. It is still a bit annoying that Github does not render *admonitions* and so on but I guess I can live with it :-)

**Comment by bilderbuchi** [comment]
Thank you, I'll see where I can go with this. My docs being on a windows network share (i.e. no proper symlinks), an mdinclude directive is the only way I can see to include out-of-tree markdown files into my Sphinx documents. Would be great if recommonmark added that feature. :-/

**Comment by segevfiner** [comment]
I guess recommonmark can add an `mdinclude` directive like m2r has for this. It would be really useful for projects wanting to include a markdown file from outside the Sphinx source tree.

**Comment by FeralBytes** [comment]
I found a better way to pull this off. Just use copyfile from python at the begining of the conf.py and copy the files that are markdown that you want to convert into the appropriate places and then they will be parsed by recommonmark.

**Comment by mitar** [comment]
I tried with symlink, but I have no idea how can I then link to it from rest file? I would also like to add custom header to it which does not exist in the md file. Include would solve both of those problems.

**Comment by Borda** [comment]
I am still failing to use `mdinclude` in my [sample project](https://github.com/Borda/py_sample-project/tree/docs) using file/document `intro.rst`
```intro.rst
Readme File
===========

.. mdinclude:: ../../README.md
```
resulting in 
```
jirka@jirka-UX430UN:~/py_sample-project/docs$ make html
Running Sphinx v1.8.5
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [] 0 added, 1 changed, 0 removed
reading sources... [100%] intro 
~/py_sample-project/docs/source/intro.rst:4: WARNING: Unknown directive type "mdinclude".
.. mdinclude:: ../../README.md
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] intro 
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.
```

**Comment by aolieman** [comment]
@Borda perhaps you misunderstood: the `mdinclude` directive is provided by the [m2r](https://github.com/miyakogi/m2r) extension, and not yet by `recommonmark`.

In the current version of recommonmark, many users can get by by symlinking their readme to their docs source directory. The main limitation of this workaround is that it will not work correctly when the docs are built on Windows.

**Comment by eric-wieser** [comment]
Perhaps related: https://github.com/sphinx-doc/sphinx/issues/2840

**Comment by CsatiZoltan** [comment]
@FeralBytes Is there a way to delete the copied files after the documentation has been built? I.e. how can I execute Python code in *conf.py* that is only executed once the documentation generation has been completed?

**Comment by FeralBytes** [comment]
@CsatiZoltan I am not sure this is possible to ensure it happens after the documentation generation is executed. But my only thought is to try a few things like, what happens if you execute the remove at the end of conf.py? Does it execute too early? If so is it possible to try and run a thread or use sleep, these are probably harder to pull off.
Sorry I can not be more help.

**Comment by CsatiZoltan** [comment]
@FeralBytes Thanks for the tips. I already tried executing remove at the end of *conf.py*. It executes before the documentation has been built.
With [some help](https://groups.google.com/g/sphinx-users/c/RwsOSK92Z-I/), [I managed to solve it](https://github.com/CsatiZoltan/CristalX/commit/fca0890c9792f8aeec5967bde484941bf26cc681). Its improvement for ReadTheDocs is [here](https://github.com/CsatiZoltan/CristalX/commit/af8fb00d7199c4a8d53df75d81caaba45485325f).
