### ISSUE TITLE
Is commonmark dependency still necessary?

### ISSUE THREAD

**Issue by ericmjl** [readthedocs/recommonmark#56]
Hi!  I'm submitting a conda-forge recipe for recommonmark, and we noticed that the recommonmark needs commonmark <= 0.5.4. The latest version of commonmark, already available on conda-forge, is 0.7+. Is it still required to use commonmark <= 0.5.4?

**Comment by ericmjl** [comment]
Posting the link to the conda-forge pull request: https://github.com/conda-forge/staged-recipes/pull/1707

**Comment by ericholscher** [comment]
Yes, commonmark was refactored after the release we're pinned to, but this library hasn't been updated to reflect that refactor.

**Comment by ericmjl** [comment]
@ericholscher thanks a lot! Will it be appropriate, then, for me to change the dependency listing on the conda-forge recipe to `commonmark` rather than `commonmark <= 0.5.4` instead?
