### ISSUE TITLE
Support footnote?

### ISSUE THREAD

**Issue by ppwwyyxx** [readthedocs/recommonmark#62]
Any plan to support the markdown footnote syntax?

Some relevant links:

https://pythonhosted.org/Markdown/extensions/footnotes.html
https://github.com/markdown-it/markdown-it-footnote

**Comment by danyeaw** [comment]
I believe that commonmark does support footnotes through [reference links](https://spec.commonmark.org/0.29/#reference-link). I created an [example](https://spec.commonmark.org/dingus/?text=%5Bfoo%5D%5B%5E1%5D%0A%0A%5B%5E1%5D%3A%20%2Furl%20%22title%22%0A) using the [^1] syntax.
