### ISSUE TITLE
Document reference with file extension not possible

### ISSUE THREAD

**Issue by mblaettler** [readthedocs/recommonmark#69]
The [Auto Doc Ref Feature](https://github.com/rtfd/recommonmark/blob/master/docs/auto_structify.md#auto-doc-ref) only works for links without file extensions.

While `[some link](link)` still links correctly to the corresponding `link.md` file, `[another link](link.md)` does not. It might be because of PR #61 since references/links aren't treated the same way.

IMHO linking files with their extension is nicer because these kind of links also work within SCMs like GitHub and GitLab.

**Comment by mblaettler** [comment]
Created PR #70. Build seems to fail due to this [Issue](https://github.com/landscapeio/prospector/issues/206).

**Comment by Niccolum** [comment]
Please do something like this
https://stackoverflow.com/a/15713991
in
https://github.com/readthedocs/recommonmark/blob/ddd56e7717e9745f11300059e4268e204138a6b1/recommonmark/parser.py#L148
