### ISSUE TITLE
Recommonmark not working with Sphinx 1.6

### ISSUE THREAD

**Issue by ratiotile** [readthedocs/recommonmark#73]
Recommonmark 0.4.0
Was working with Sphinx 1.5. When I updated to 1.6, build no longer works.

```
Exception occurred:
  File "python3.4/site-packages/recommonmark/states.py", line 134, in run_role
    content=content)
TypeError: 'NoneType' object is not callable
```

**Comment by ratiotile** [comment]
Sphinx issue for reference: https://github.com/sphinx-doc/sphinx/issues/3800

**Comment by lorengordon** [comment]
Reposting from https://github.com/sphinx-doc/sphinx/issues/3800#issuecomment-308592852, since that issue was closed, and it seems even though the exception doesn't occur with code from master, recommonmark is still not generating links quite right...

> ...at least part of the problem appears to be that recommonmark hasn't released a version in a bit. The code in that diff isn't present in the master branch. It was removed in the [last commit](https://github.com/rtfd/recommonmark/commit/8baf238562c2f7c9bea603e352c3a94f51905a3e) that modified that file.
>
> I adjusted my requirements file to build from the recommonmark master branch and was able to get it to work, sort of. Needed to also modify link references from `[file](file.md)` to `[file](file.html)` to get the references to point to a page that will actually load, which is kind of awful.
