### ISSUE TITLE
support Chinese title not well？

### ISSUE THREAD

**Issue by iromise** [readthedocs/recommonmark#80]
If I open the `:numbered:` option, It seems recommonmark do not work well with Chinese title, such as 

> # 测试
>## 你
>## 我
>## 他
but works well with English title, such as
># 1
>## a
>## b
>## c
Both can generate the toc well, but the content with Chinese just do not match the toc, which is
> 1.3. 测试
>1.3. 你
>1.3. 我
>1.3. 它

**Comment by fyears** [comment]
duplicated of https://github.com/rtfd/recommonmark/issues/83

**Comment by iromise** [comment]
thanks, I will try it.
