### ISSUE TITLE
Cannot render RST contents page from within markdown

### ISSUE THREAD

**Issue by multimeric** [readthedocs/recommonmark#94]
If you use the following RST block, which is supposed to generate a table of contents (http://docutils.sourceforge.net/docs/ref/rst/directives.html#table-of-contents):
````
```eval_rst
.. contents::
    :local:
```
````

Sphinx will throw a warning, saying
```
WARNING: The "contents" directive may not be used within topics or body elements.
```

I suspect this is something to do with how recommonmark converts the markdown to RST. Is it putting this directive inside a topic/body element such that this is happening? Is it possible to fix this?

**Comment by nmandya** [comment]
I am facing the exact same issue. Is there any fix or workaround for this? Thanks.
