### ISSUE TITLE
'ascii' codec can't encode character u'\u7b2c'

### ISSUE THREAD

**Issue by zhex900** [readthedocs/recommonmark#97]
My Markdown files are in UTF-8 with Chinese characters.

sphinx-build gave me this error. Is the problem with UTF-8?

'ascii' codec can't encode character u'\u7b2c' in position 0: ordinal not in range(128)

this is my `conf.py`
`````
# -- Extension configuration -------------------------------------------------
def setup(app):
    app.add_config_value('recommonmark_config', {
        'auto_toc_tree_section': 'Contents',
        'enable_eval_rst': True,
        'enable_auto_doc_ref': True,
    }, True)
    app.add_transform(AutoStructify)

**Comment by hengyunabc** [comment]
Try to use python3, it works for me.
